# Generated by Django 5.0 on 2023-12-17 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lighting", models.BooleanField(default=False)),
                ("acid_actuator", models.BooleanField(default=False)),
                ("alkaline_actuator", models.BooleanField(default=False)),
                ("nutrient_actuator", models.BooleanField(default=False)),
                ("fans_rpm", models.IntegerField(default=0)),
                ("accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FilePathField()),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph", models.FloatField(default=0.0)),
                ("ec", models.FloatField(default=0.0)),
                ("air_temp", models.FloatField(default=0.0)),
                ("humidity", models.FloatField(default=0.0)),
                ("water_flow", models.BooleanField(default=False)),
                ("lighting", models.BooleanField(default=False)),
                ("full_water_tank", models.BooleanField(default=False)),
                ("acid_actuator", models.BooleanField(default=False)),
                ("alkaline_actuator", models.BooleanField(default=False)),
                ("nutrient_actuator", models.BooleanField(default=False)),
                ("fans_rpm", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnknownModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=50)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("picture", models.ImageField(blank=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("planted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spinach.profilemodel",
                    ),
                ),
            ],
        ),
    ]
