# Generated by Django 5.0 on 2023-12-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinach', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnknownModel',
        ),
    ]
